In [2]:
import pandas as pd
import numpy as no
import matplotlib.pyplot as plt
import seaborn as sns


data = pd.read_csv("Data/binary_train_cleaned.csv")
X = data.drop('SalePrice', axis=1)
y = data['SalePrice']

X

,Neighborhood_Sawyer,MasVnrType_Stone,Exterior1st_AsbShng,Exterior1st_BrkComm,Exterior1st_BrkFace,Exterior1st_CBlock,Exterior1st_CemntBd,Exterior1st_HdBoard,MasVnrType_BrkFace,Exterior1st_ImStucc,...,Neighborhood_ClearCr,Neighborhood_NAmes,Neighborhood_NPkVill,Neighborhood_MeadowV,Neighborhood_IDOTRR,Neighborhood_Gilbert,Neighborhood_Edwards,Neighborhood_Crawfor,Neighborhood_Mitchel,Neighborhood_OldTown
0,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1407,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
1408,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1409,False,False,False,False,False,False,True,False,True,False,...,False,False,False,False,False,False,False,True,False,False
1410,False,False,False,False,False,False,False,False,True,False,...,False,True,False,False,False,False,False,False,False,False
1411,False,False,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,True,False,False,False

# Precent of Trues
We will ignore those that have less then `5%` of trues. (These features distinguishes less than 71 observations)

In [26]:
0.05*data.shape[0]

70.60000000000001

In [30]:
cols = X.columns

cut_off = 0.05
precent = {}
for col in cols:
    precent[col] = X[col].sum()/X.shape[0]

df_p = pd.DataFrame.from_dict(precent, orient='index')
df_p.columns = ["%"]
df_p.sort_values(by="%", ascending=True, inplace=True)


df_p[df_p['%'] > 0.05]

                             %
Neighborhood_Sawyer   0.050992
Neighborhood_NWAmes   0.051700
GarageType_NA         0.052408
Neighborhood_NridgHt  0.053116
Neighborhood_Gilbert  0.054533
PavedDrive_N          0.056657
Neighborhood_Somerst  0.058782
GarageType_BuiltIn    0.060198
Electrical_FuseA      0.062323
Neighborhood_Edwards  0.063031
LotConfig_CulDSac     0.064448
Exterior1st_Plywood   0.072946
Neighborhood_OldTown  0.078612
SaleType_New          0.084278
MasVnrType_Stone      0.090652
Exterior2nd_Plywood   0.095609
Foundation_BrkTil     0.102691
Neighborhood_CollgCr  0.104816
Exterior2nd_Wd Sdng   0.135269
Exterior1st_Wd Sdng   0.142351
Exterior2nd_HdBoard   0.143768
Exterior2nd_MetalSd   0.148017
MSZoning_RM           0.151558
Neighborhood_NAmes    0.152266
Exterior1st_MetalSd   0.152266
Exterior1st_HdBoard   0.154391
LotConfig_Corner      0.181303
RoofStyle_Hip         0.196176
GarageType_Detchd     0.261331
Exterior2nd_VinylSd   0.347734
Exterior1st_VinylSd   0.354816
Foundation_CBlock     0.442635
Foundation_PConc      0.448300
GarageType_Attchd     0.603399
LotConfig_Inside      0.718839
RoofStyle_Gable       0.781161
MSZoning_RL           0.786827
SaleType_WD           0.866856
MasVnrType_BrkFace    0.898725
Electrical_SBrkr      0.920680
PavedDrive_Y          0.922805
CentralAir            0.942635
HasGarage             0.947592
Heating_GasA          0.981586
Street_Pave           0.995751

In [40]:
columns = list(df_p[df_p['%'] > 0.05].index)
new_data = data[columns]

new_data

,Neighborhood_Sawyer,Neighborhood_NWAmes,GarageType_NA,Neighborhood_NridgHt,Neighborhood_Gilbert,PavedDrive_N,Neighborhood_Somerst,GarageType_BuiltIn,Electrical_FuseA,Neighborhood_Edwards,...,RoofStyle_Gable,MSZoning_RL,SaleType_WD,MasVnrType_BrkFace,Electrical_SBrkr,PavedDrive_Y,CentralAir,HasGarage,Heating_GasA,Street_Pave
0,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1407,False,False,False,False,True,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
1408,False,True,False,False,False,False,False,False,False,False,...,True,True,True,False,True,True,True,True,True,True
1409,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
1410,False,False,False,False,False,False,False,False,True,False,...,False,True,True,True,False,True,True,True,True,True
1411,False,False,False,False,False,False,False,False,False,True,...,True,True,True,True,True,True,True,True,True,True

# Group Test
from [EDA_intro](3_EDA_intro.ipynb) we know that we can't assume that target has normal distribution. That is why we will use Whitney U-test.