In [1]:
import pandas as pd
import numpy as np

binary = pd.read_csv('Data/binary_train_selected.csv')
ordinal = pd.read_csv('Data/ordinal_train_selected.csv')
numerical = pd.read_csv('Data/num_train_selected.csv')
time = pd.read_csv('Data/time_train_selected.csv')

full_data = pd.concat([binary, ordinal, numerical, time], axis=1).drop('Unnamed: 0', axis=1)


full_data

,Foundation_PConc,GarageType_Detchd,GarageType_Attchd,Exterior2nd_VinylSd,MSZoning_RM,Foundation_CBlock,Neighborhood_NAmes,MSZoning_RL,Exterior1st_VinylSd,SaleType_New,...,Garage_index,Condition_index,Living_Area,OpenSF,Luxury_index,Comf_idx,FullBath,LotFrontage,YearBuilt,SalePrice
0,True,False,True,True,False,False,False,True,True,False,...,5,30.0,38.247157,7.440869,4.317259,13.873467,1.712883,28.197481,2003,208500
1,False,False,True,False,False,True,False,True,False,False,...,5,17.5,34.902620,4.825198,6.036094,15.530623,1.712883,32.996821,1976,181500
2,True,False,True,True,False,False,False,True,True,False,...,5,30.0,38.917216,6.976956,4.001528,14.329585,1.712883,29.178737,2001,223500
3,False,True,False,False,False,False,False,True,False,False,...,4,35.0,38.036693,3.754613,3.030397,13.374408,0.911265,26.535234,1915,140000
4,True,False,True,True,False,False,False,True,True,False,...,5,30.0,40.236550,12.468098,5.501664,16.435368,1.712883,34.235344,2000,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1407,True,False,True,True,False,False,False,True,True,False,...,5,30.0,38.402028,3.897520,0.246362,13.513207,1.712883,27.204315,1999,175000
1408,False,False,True,False,False,True,False,True,False,False,...,4,12.5,36.528185,7.862977,5.841068,16.189255,1.712883,34.542537,1978,210000
1409,False,False,True,False,False,False,False,True,False,False,...,5,70.0,39.735171,4.337072,3.349038,14.325773,1.712883,28.525856,1941,266500
1410,False,False,True,False,False,True,True,True,False,False,...,4,12.5,34.245881,4.969695,2.916682,13.947536,0.911265,29.178737,1950,142125
1411,False,False,True,False,False,True,False,True,False,False,...,6,12.5,34.928774,9.922530,5.897605,15.022426,0.911265,31.425563,1965,147500

# Test and Train data split

In [2]:
np.random.seed(42)

N = len(full_data)
idx = np.arange(0, N)
np.random.shuffle(idx)

train = full_data.iloc[idx[:int(0.8*N)]]
test = full_data.iloc[idx[int(0.8*N):]]

train

,Foundation_PConc,GarageType_Detchd,GarageType_Attchd,Exterior2nd_VinylSd,MSZoning_RM,Foundation_CBlock,Neighborhood_NAmes,MSZoning_RL,Exterior1st_VinylSd,SaleType_New,...,Garage_index,Condition_index,Living_Area,OpenSF,Luxury_index,Comf_idx,FullBath,LotFrontage,YearBuilt,SalePrice
741,True,False,True,False,False,False,False,True,False,False,...,6,60.000,35.628359,3.590896,3.875578,9.414997,0.911265,15.604698,1995,270000
865,False,True,False,False,False,True,True,True,False,False,...,4,37.500,36.329019,0.000000,0.154925,13.298420,0.911265,26.535234,1949,122900
339,True,False,True,False,False,False,False,True,False,True,...,6,30.000,42.542947,3.468843,5.547298,13.581823,1.712883,25.179280,2005,437154
192,False,False,False,False,True,True,False,False,False,False,...,0,46.875,37.573278,5.672260,0.000000,17.129117,0.911265,36.667137,1912,104000
203,False,False,True,False,False,True,True,True,False,False,...,5,15.000,34.079853,3.168412,4.371354,14.938750,0.911265,31.425563,1964,145000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1220,True,False,True,False,False,False,True,False,False,False,...,6,60.000,34.165046,8.774702,4.159288,9.562460,1.712883,17.186882,1998,181000
1185,False,True,False,True,False,True,True,True,True,False,...,4,17.500,33.420319,9.100719,4.004645,14.336896,0.911265,30.469668,1965,147000
1167,True,False,True,True,False,False,False,True,True,False,...,5,10.000,36.102675,10.752007,4.472627,14.451533,1.712883,29.826615,2003,200000
517,True,False,True,True,False,False,False,True,True,False,...,6,30.000,37.475508,7.784056,1.253723,14.874775,1.712883,31.108063,2004,178000
1069,True,False,True,True,False,False,False,True,True,False,...,5,30.000,38.380621,8.123609,1.253723,4.453286,1.712883,0.000000,2000,181000

## Dummy Regressor
As a reference point for training and test data

In [3]:
from sklearn.dummy import DummyRegressor
from sklearn.metrics import mean_squared_error

dummy_r = DummyRegressor(strategy='mean')


dummy_r.fit(train.drop(['SalePrice'], axis=1), train['SalePrice'])

pred = dummy_r.predict(test.drop(['SalePrice'], axis=1))

MSE =  mean_squared_error(pred, test['SalePrice'])

print(f'Dummy regressor (calculated mean) got a score: {MSE=}')

Dummy regressor (calculated mean) got a score: MSE=6696884944.645073

## Save

In [5]:
train.to_csv('Data/final_train.csv')
test.to_csv('Data/final_test.csv')
print("Data Saved")

Data Saved