In [1]:
import pandas as pd

train_data = pd.read_csv('Data/final_train.csv')
test_data = pd.read_csv('Data/final_test.csv')

train_x, train_y = train_data.drop('SalePrice', axis=1), train_data['SalePrice']
test_x, test_y = test_data.drop('SalePrice', axis=1), test_data['SalePrice']

train_x

,Unnamed: 0,Foundation_PConc,GarageType_Detchd,GarageType_Attchd,Exterior2nd_VinylSd,MSZoning_RM,Foundation_CBlock,Neighborhood_NAmes,MSZoning_RL,Exterior1st_VinylSd,...,Bsmt_index,Garage_index,Condition_index,Living_Area,OpenSF,Luxury_index,Comf_idx,FullBath,LotFrontage,YearBuilt
0,741,True,False,True,False,False,False,False,True,False,...,5,6,60.000,35.628359,3.590896,3.875578,9.414997,0.911265,15.604698,1995
1,865,False,True,False,False,False,True,True,True,False,...,3,4,37.500,36.329019,0.000000,0.154925,13.298420,0.911265,26.535234,1949
2,339,True,False,True,False,False,False,False,True,False,...,7,6,30.000,42.542947,3.468843,5.547298,13.581823,1.712883,25.179280,2005
3,192,False,False,False,False,True,True,False,False,False,...,2,0,46.875,37.573278,5.672260,0.000000,17.129117,0.911265,36.667137,1912
4,203,False,False,True,False,False,True,True,True,False,...,4,5,15.000,34.079853,3.168412,4.371354,14.938750,0.911265,31.425563,1964
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1124,1220,True,False,True,False,False,False,True,False,False,...,7,6,60.000,34.165046,8.774702,4.159288,9.562460,1.712883,17.186882,1998
1125,1185,False,True,False,True,False,True,True,True,True,...,6,4,17.500,33.420319,9.100719,4.004645,14.336896,0.911265,30.469668,1965
1126,1167,True,False,True,True,False,False,False,True,True,...,9,5,10.000,36.102675,10.752007,4.472627,14.451533,1.712883,29.826615,2003
1127,517,True,False,True,True,False,False,False,True,True,...,4,6,30.000,37.475508,7.784056,1.253723,14.874775,1.712883,31.108063,2004
1128,1069,True,False,True,True,False,False,False,True,True,...,2,5,30.000,38.380621,8.123609,1.253723,4.453286,1.712883,0.000000,2000

## Matric Function

In [3]:
import numpy as np
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

def metric(y_hat, y_true,features_shape):
    n,p = features_shape
    r2 = r2_score(y_true, y_hat)
    socres = {
        "MAE": mean_absolute_error(y_true, y_hat),
        "MSE": mean_squared_error(y_true, y_hat),
        "RMSE": np.sqrt(mean_squared_error(y_true, y_hat)),
        "R2": r2,
        "Adjusted R2":  1 - (1 - r2) * (n - 1) / (n - p - 1)
    }

    df_score = pd.DataFrame(socres.items(), columns=["Metric","Value"])

    return df_score

metric(train_y, train_y, train_x.shape)

        Metric  Value
0          MAE    0.0
1          MSE    0.0
2         RMSE    0.0
3           R2    1.0
4  Adjusted R2    1.0